### ISSUE TITLE
Error while trying start example

### ISSUE THREAD

**Issue by budarin** [axept/prejss#13]
I try to run example project from package and get an error:
ReferenceError: Unknown plugin "transform-prejss" specified in "\prejss\\examples\\basic\\.babelrc"

**Comment by DenisIzmaylov** [comment]
Thanks for your feedback!

Have you tried to run `npm install` in "basic" directory?

**Comment by budarin** [comment]
Shure, of couse! )14:20, 14 марта 2017 г., Denis Izmaylov <notifications@github.com>:Thanks for your feedback!
Have you tried to run npm install in "basic" directory?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




С уважением Бударин Вадим

**Comment by DenisIzmaylov** [comment]
Very interesting. So we'll try to fix it in next 2 days.

**Comment by BrRenat** [comment]
Another problem. In example project and in my project on start:
Module not found: Error: Cannot resolve module 'prejss-postcss-parser' in projectroot\node_modules\prejss\lib
 @ ./~/prejss/lib/index.js 16:27-59

**Comment by DenisIzmaylov** [comment]
Thanks for details. I'll try to review it in next two days. But feel free to make a PR. It's simple and fun!

**Comment by DenisIzmaylov** [comment]
> Another problem. In example project and in my project on start:
> Module not found: Error: Cannot resolve module 'prejss-postcss-parser' in 

@BrRenat Sorry for a bit delay. Just fixed it. Could you please try again?

**Comment by DenisIzmaylov** [comment]
@budarin, just checked for your issue. It seems everything is working correctly now. Could you please check up?

**Comment by DenisIzmaylov** [comment]
Also I've just published example React.js application with PreJSS, have a joy:

+ https://github.com/axept/prejss-example-app

**Comment by budarin** [comment]
![default](https://cloud.githubusercontent.com/assets/8055157/24391233/7f1c0c7a-1396-11e7-92dc-59ff2118c673.png)

There are some problems:
- i have not found any mention about nodemon
- commands are not cross operating system

**Comment by DenisIzmaylov** [comment]
That's truth. Thank you for your feedback. I've removed basic example:

+ https://github.com/axept/prejss/tree/master/examples

It's not a good practice to keep large example in the same repo since we have to keep traction on each project separately.

Please try it:

+ https://github.com/axept/prejss-example-app

This example already contains a mention about nodemon and uses `cross-env`.

Please give any feedback once you have success with that.

**Comment by BrRenat** [comment]
@DenisIzmaylov well done! Everything works fine. But I did not check the postcss plugins yet. I think with it no problem. In JetBrains IDEA we can add `//language=PostCSS` for postcss highlighting and autocomplete.
Example  `styles.js`
```
import preJSS from 'prejss'
import theme from 'theme'

//language=PostCSS
const styles = preJSS`
  button {
    background: ${theme.color.main};
  }
`

export default styles

```

**Comment by DenisIzmaylov** [comment]
@BrRenat Omg. Really? Will it work? Could you please provide a screenshot from JetBrains IDEA?

```js
import preJSS from 'prejss'
import theme from 'theme'

// language=PostCSS
const styles = preJSS`
  button {
    background: ${theme.color.main};
  }
`

```

**Comment by BrRenat** [comment]
@DenisIzmaylov yea))). Don't forget install postcss plugin in idea.
PHPStorm WebStorm 2016, 2017
![image](https://cloud.githubusercontent.com/assets/16529522/24467048/02403882-14c4-11e7-808d-3f222f74d1e1.png)

**Comment by BrRenat** [comment]
@DenisIzmaylov can we use prejss in devDependencies? 
In react-boilerplate i install prejss into dependencies and after webpack build dll i have error `Module not found: Error: Can't resolve fs, module.. etc ` i understand why we have that error. But I do not understand how i can use prejss only in dev.

**Comment by DenisIzmaylov** [comment]
Wow! Really awesome. Could I use this screenshot for my talk on MoscowJS today?

**Comment by BrRenat** [comment]
@DenisIzmaylov  Looks like I'm late, of course

**Comment by BrRenat** [comment]
node 6 not supported

`Object.entries is not a function`

**Comment by DenisIzmaylov** [comment]
Anyway thanks :) BTW Should we support Node.js 6?

**Comment by DenisIzmaylov** [comment]
Is there any problems on this issue still exists which we have to fix/to do?

**Comment by budarin** [comment]
standalone demo project works fine.
Thanks

**Comment by DenisIzmaylov** [comment]
@budarin Thank you for your effort. Looking forward for your pull requests! 🎉
